version: '3.8'

services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - e-commerce-app-vol:/data

volumes:
    e-commerce-app-vol: